# Chapter1

## Import audio file

In [3]:
import wave

# Create audio file wave object
good_morning = wave.open("datasets/good-morning.wav", 'r')

# Read all frames from wave object 
signal_gm = good_morning.readframes(-1)

In [4]:
# View first 10
print(signal_gm[:10])

b'\xfd\xff\xfb\xff\xf8\xff\xf8\xff\xf7\xff'


In [5]:
type(signal_gm)

bytes

## Converting bytes to integers

In [6]:
import numpy as np
signal_gm = np.frombuffer(signal_gm, dtype='int16')

In [7]:
signal_gm[:10]

array([ -3,  -5,  -8,  -8,  -9, -13,  -8, -10,  -9, -11], dtype=int16)

In [8]:
# length of numpy array
len(signal_gm)

249984

## Finding the frame rate

In [10]:
frame_rate_gm = good_morning.getframerate()
frame_rate_gm

48000

## Finding sound wave timestamps

In [11]:
np.linspace(start=1, stop=10, num=10) # return evenly spaced numbers over a specified interval.

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [13]:
time_gm = np.linspace(start=0, 
            stop=len(signal_gm)/frame_rate_gm, 
            num=len(signal_gm))

time_gm[:10]

array([0.00000000e+00, 2.08334167e-05, 4.16668333e-05, 6.25002500e-05,
       8.33336667e-05, 1.04167083e-04, 1.25000500e-04, 1.45833917e-04,
       1.66667333e-04, 1.87500750e-04])

In [14]:
len(time_gm)

249984